excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://alie9ja.github.io
title: The Alie9ja Thought Show
email: alie9ja@tuta.io
author: alie9ja
description: Turn on, boot up, jack in.
paginate: 9
google_analytics: 
